name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GOFLAGS: -mod=readonly

jobs:
  test:
    name: test/(${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-26.04
          - xcode-27
          - windows-2025
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          check-latest: true
      - run: go build ./...
      - run: go vet ./...
      - name: Test and take a coverage
        if: matrix.os != 'windows-2025'
        env:
          GOTESTSUM_FORMAT: standard-verbose
        run: >-
          go tool gotestsum --junitfile _test_results/tests.xml --
          -race -count=1 -covermode=atomic -coverpkg=./... -coverprofile=coverage.out ./...
      - name: Upload coverage to Codecov
        if: success() && matrix.os != 'windows-2025'
        uses: codecov/codecov-action@v7
        with:
          report_type: coverage
          files: coverage.out
          flags: ${{ runner.os }}-${{ runner.arch }}
          use_oidc: true
          verbose: true
      - name: Upload test results to Codecov
        if: ${{ !cancelled() && matrix.os != 'windows-2025' }}
        uses: codecov/codecov-action@v7
        with:
          report_type: test_results
          files: _test_results/tests.xml
          flags: ${{ runner.os }}-${{ runner.arch }}
          use_oidc: true

  lint:
    runs-on: ubuntu-26.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          check-latest: true
      - uses: golangci/golangci-lint-action@v9
        with:
          version: latest

  verify:
    runs-on: ubuntu-26.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          check-latest: true
      - run: go mod tidy -diff
      - run: go generate ./internal/license/...
      - run: git diff --exit-code
