name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GOFLAGS: -mod=readonly

jobs:
  test:
    name: test/(${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-26.04
          - xcode-27
          - windows-2025
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          check-latest: true
      - run: go build ./...
      - run: go vet ./...
      - run: go test -race -count=1 -cover ./...
        if: matrix.os != 'windows-2025'

  lint:
    runs-on: ubuntu-26.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          check-latest: true
      - uses: golangci/golangci-lint-action@v9
        with:
          version: latest

  verify:
    runs-on: ubuntu-26.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          check-latest: true
      - run: go mod tidy -diff
      - run: go generate ./internal/license/...
      - run: git diff --exit-code
